* Natural deploy

** Motivation
Have you ever felt when using any declarative type of program
that is used for deployment. Its really unnatural to use (i.e you are a YAML developer). This is in
comparison to using any programming language (Which has advanced static type checkers, error diagnosis etc...).

The 2nd issue is it's really hard to setup servers and can only work with nodes which have public IPs. Most orchestration
tools are built on the basis to use static IPs and fixed ports. 

The effect of this move is that you can easily get vendor locked and you are less likely to choose the economical
choice of owning your own hardware. We have lesser gratefullness of how complex problems were abstracted in simple tools
like FTP, GIT, OrgMode or the design principles of Unix utilities.

The aim of "Natural deploy" is to be library build on top of P2PRC to make it as easy as running a binary to deloy your
custom tasks to your servers. This will gives you the flexibility to truly customise building your orchestration layer to
run your programs across your cluster of servers which can be situated anywhere.

** How to install
The only requirement if you are compiling from source is to have the Go compiler.
We will show this example by demonstrating a simple example which consists of 3 computers:

*** The first computer (Root node):
Which is has a static public address. This is required to traverse traffic for your computers
behind NAT.
- Create a file called root.go
- Copy the following below into root.go
#+begin_src go
package main

import (
    "fmt"
    natural_deploy "github.com/Akilan1999/P2PRC-natural-deploy"
    "github.com/Akilan1999/p2p-rendering-computation/client"
    "os"
)

func main() {

    // Checking if the lock file exists
    // if not configures the root node
    _, err := os.Stat("Root.lock")
    if err != nil {
        // Create the root node configuration
        rootNode, err := natural_deploy.CreateRootNode("RootNode")
        if err != nil {
            fmt.Println(err)
            os.Exit(1)
        }

        fmt.Println("----- Root Node information -------")
        client.PrettyPrint(rootNode)
        fmt.Println("-----------------------------------")
        fmt.Println("Daemon starting .....")

        os.Create("Root.lock")
    }

    err = natural_deploy.RunDaemon()
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
        return
    }
    fmt.Println("Daemon started .....")

    for {

    }
}
#+end_src
- Compile root.go
#+begin_src bash
  go build root.go
  # Run the binary as a background process
  ./root &
#+end_src

- Store the output
 #+begin_src json
    {
       "Name": "RootNode",
       "MachineUsername": "",
       "IPV4": "<public ipv4 address>", // The public address of your root server
       "IPV6": "",
       "Latency": 0,
       "Download": 0,
       "Upload": 0,
       "ServerPort": "8088", // The default port of the root node 
       "UDPServerPort": "",
       "BareMetalSSHPort": "22",
       "NAT": false,
       "EscapeImplementation": "",
       "ProxyServer": false,
       "UnSafeMode": false,
       "PublicKey": "",
       "CustomInformation": ""
    }
 #+end_src

*** The 2nd computer (The server behind NAT)
This could for instance an old laptop which you would want to bring back to life.

- Create the file server.go
- Add the following to the server.go file. We are going call this server "Test-Server".
#+begin_src go
  package main

import (
	"fmt"
	natural_deploy "github.com/Akilan1999/P2PRC-natural-deploy"
	"os"
)

func main() {
	_, err := os.Stat("Regular.lock")
	if err != nil {
		// Create the root node to be added
		var rootnode natural_deploy.RootNode
		// make sure to fill in "<>" area with the appropriate information
		rootnode.IPAddress = "<public ipv4 address>"
		rootnode.Port = "<ServerPort>" // (i.e 8088 by default) 

		err := natural_deploy.CreateRegularNode("Test-Server", &rootnode)
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
			return
		}
		os.Create("Regular.lock")
	}

	// Start the daemon
	err = natural_deploy.RunDaemon()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
		return
	}

	for {

	}
}
#+end_src

- Compile server.go
  #+begin_src bash
    go build server.go
    # Run the binary as a background process
    ./server &
 #+end_src

*** The 3rd Computer (Task machine)
This is can be your current laptop which can remotely deploy tasks to your self hosted server.
We are going to run a simple python server on the remote machine called "Test-Server". We will
start the task which will deploy the python server from our local machine to the "Test-Server"
machine which will then start the server and will internally call P2PRC function calls to provide
an static ip and port number from the Root node. Therefore escaping NAT which allows you to self
host. 
- Create the deploy script which we will call "test.sh" (The python server runs locally in 8000).
#+begin_src bash
  nohup python3 -m http.server 8000 > server.log 2>&1 &
#+end_src
- Create a script to kill the deployed python server. We will call this "kill.sh".
#+begin_src bash
  kill -9 $(lsof -t -i:8000)
#+end_src
- Create the file task.go
- Add the following to task.go
#+begin_src go
      package main

    import (
        "fmt"
        natural_deploy "github.com/Akilan1999/P2PRC-natural-deploy"
        "github.com/Akilan1999/p2p-rendering-computation/client"
        "github.com/Akilan1999/p2p-rendering-computation/p2p"
        "os"
        "time"
    )

    func main() {
        _, err := os.Stat("Task.lock")
        if err != nil {
            // If you want to add a custom root node
            var rootnode natural_deploy.RootNode
            // make sure to fill in "<>" area with the appropriate information
            rootnode.IPAddress = "<public ipv4 address>"
            rootnode.Port = "<ServerPort>"
            // Name of the task machine
            natural_deploy.CreateTaskMachine("Task", &rootnode) 
        }

        // Create a 5 second delay from mapping port
        time.Sleep(5 * time.Second)

        // ------------------- Create a task -----------------
        var task natural_deploy.Task
        task.Name = "Test"
        task.TaskFile = "test.sh"
        task.KillTaskFile = "kill.sh"

        // Get all node information
        table, err := p2p.ReadIpTable()
        if err != nil {
            fmt.Println(err)
            os.Exit(1)
            return
        }

        fmt.Println("IP table read")

        // Searching for the information of a particular
        // node information (In this example Test-2 node)
        var machineInfo p2p.IpAddress
        for i, _ := range table.IpAddress {
            if table.IpAddress[i].Name == "Test-1" {
                machineInfo = table.IpAddress[i]
            }
        }

        fmt.Println(machineInfo)

        // Allocate ports
        var port client.ResponseMAPPort
        port.PortNo = "8000"
        task.ExposedPorts = append(task.ExposedPorts, &port)

        task.NodeInfo = &machineInfo
        // ---------------------------------------------------------

        err = task.CreateTask()
        if err != nil {
            fmt.Println(err)
            os.Exit(1)
            return
        }

        // Create a 10 second delay from mapping port
        time.Sleep(10 * time.Second)

        err = task.KillTask()
        if err != nil {
            fmt.Println(err)
            os.Exit(1)
            return
        }

    }

#+end_src
- Compile server.go
  #+begin_src bash
     go build task.go
     # Run the binary as a background process
     ./task &
  #+end_src
